import type { RegionValue } from './regions'

/**
 * Communes & chefs-lieux du Sénégal par région — source officielle
 * senegalouvert/Decoupage-Administratif (ODbL) : départements + communes
 * d'arrondissement + communes rurales, normalisés et dédupliqués.
 * 415 entrées / 14 régions. Découpage 2008, non 100% exhaustif →
 * option « Autre » de saisie libre en complément. GUIC-432.
 */
export const COMMUNES_BY_REGION: Record<RegionValue, readonly string[]> = {
  Dakar: ["Bargny Rufisque Nord", "Biscuiterie", "Cambérène", "Dakar", "Dakar - Plateau", "Dalifort", "Diamagueune Sicap Mbao", "Diamniadio Rufisque Ouest", "Dieuppeul – Derklé", "Djidah Thiaroye Kao", "Golf Sud", "Gorée", "Grand Dakar", "Grand Yoff", "Guediawaye", "Guinaw Rail Nord", "Guinaw Rail Sud", "H.l.m", "Keur Massar", "Malika", "Mbao", "Médina Gounass", "Ndiarème Limamoulaye", "Ngor", "Ouakam", "Parcelles Assainies", "Patte D’Oie", "Pikine Est", "Pikine Nord", "Pikine Ouest", "Rufisque", "Rufisque Est", "Sam Notaire", "Sangalkam Yenne", "Sicap - Liberté", "Sébikotane", "Thiaroye Gare", "Thiaroye sur Mer", "Wakhinane Nimzath", "Yeumbeul Nord", "Yeumbeul Sud", "Yoff"],
  Thies: ["Chérif Lo", "Darou Khoudoss", "Fandène", "Fissel", "Keur Moussa Diender", "Koul", "Mbayène", "Mbour", "Mont Rolland", "Méouane", "Mérina Dakhar", "Ndiaganiao", "Ndiéyène Sirakh", "Ngandiouf", "Ngoudiane", "Nguéniène", "Niakhène", "Notto", "Notto Gouye Diama", "Pire Goureye", "Pékèsse", "Sandiara", "Sessene", "Sindia Mbour Malicounda", "Tassète", "Taïba Ndiaye", "Thies", "Thilmakha", "Thiénaba", "Tivaouane", "Touba Toul"],
  Diourbel: ["Baba Garage", "Bambey", "Dalla Ngabou", "Dendèye Gouy Gui", "Dinguiraye", "Diourbel", "Gade Escale", "Gawane", "KAEL Touba Mboul", "Keur Ngalgou", "Keur Samba Kane", "Lambaye", "Madina", "Mbacke", "Missirah", "Ndangalma", "Ndankh Séne", "Ndindy", "Ndioumane Taïba Thièkène", "Ndondol", "Ndoulo", "Nghaye", "Ngogom", "Ngohe", "Pattar", "Réfane", "Sadio", "Taïba Moutoupha", "Taïf", "Thiakhar", "Tocky Gare", "Touba Fall", "Touba Mosquée", "Touré Mbondé"],
  Fatick: ["Bassoul", "Colobane", "Diakhao", "Diaoulé", "Diarrère", "Dionewar", "Diossong", "Diouroup", "Djilasse", "Djilor", "Djirnda", "FATICK Dioffior", "Fimela", "Foundiougne", "Gossas", "Keur Saloum Diané", "Keur Samba Guèye", "Loul Sessène", "Mbar", "Mbéllacadiao", "Ndiene Lagan", "Ndiop", "Ngayokhème", "Niakhar", "Nioro Alassane Talla", "Ouadiour", "Palmarin Facao", "Patar", "Patar Lia", "Tattaguine", "Tobacouta"],
  Kaolack: ["Dya", "Gagnick", "Gainthe Kaye", "Kaolack", "Kayemor", "Keur Baka", "Keur Maba Diakhou", "Keur Madongo", "Keur Socé", "Khelcom - Birane", "Latmingué", "Mbadakhoune", "Mboss", "Médina Sabakh", "Ndiaffate", "Ndiago", "Ndiedieng", "Ndiébel", "Ndramé Escale", "Ngathie Naoudé", "Ngayene", "Nioro", "Ourour", "Paos Koto", "Porokhane", "Taïba Niassène", "Thiaré", "Thiomby", "Wack Ngouna"],
  Kaffrine: ["Birkelane", "Boulel", "Darou Miname 2", "Diamagadio", "Dianké Souf", "Diokoul Belbouck", "Fass Thièkène", "Gniby", "Ida Mouride", "Kaffrine", "Kahi", "Kathiotte", "Keur Mboucki", "Khelcom", "Koungheul", "Lour Escale", "Mabo", "Maka Yop", "Malem Hoddar", "Missirah Wadène", "Médinatoul Salam 2", "Ndiognick", "Ndioum Ngainth", "Ngainthe Pathé", "Ribot Escale", "Sagna", "Saly Escale", "Touba Mbella"],
  Louga: ["Bandegne Ouolof", "Darou Marnane", "Darou Mousty", "Dealy", "Diokoul Diawrigne", "DJOLOF Boulal", "Dodji", "Gande", "Kab Gaye", "Kamb Mbeuleukhé", "Kanène Ndiob", "Kebemer", "Kéle Gueye", "Labgar", "Linguere", "Loro", "Louga", "Léona", "Mbacké Cajor", "Mbadiane", "Mboula", "Mbédiene", "Ndande", "Ndiagne", "Ndoyene", "Ngourane Ouolof", "Ngueune Sarr", "Nguidilé", "Niomré", "Ouarkhokh", "Pété Ouarack", "Sagatta Djolof", "Sagatta Gueth", "Sakal", "Sam Yabal", "Syer", "Thiamène", "Thiamène Passe", "Thieppe", "Thiolom Fall", "Touba Mérina", "Téssékéré Forage"],
  Saint_Louis: ["Aéré Lao", "Bokhol", "Dagana", "Dodel", "Fanaye", "Fass Ngom", "Gamadji Saré", "Gandon", "Guedé Village", "Madina Diathbé", "Mbane", "Mbolo Birane", "Méry", "Ndiayene Peindao", "Ndiébène Gandiole", "Ngnith", "Podor", "Pété", "Ronkh", "Saint Louis"],
  Matam: ["Aouré", "Bokidiawé", "Bokiladji", "Dabia", "Des Agnam", "Kanel", "Lougré Thioly", "Matam", "Nabadji Civol", "Ndendory", "Ogo", "Orkadiéré", "Oréfondé", "Oudalaye", "Ranerou Ferlo", "Vélingara", "Wouro Sidy"],
  Tambacounda: ["Bakel", "Bala", "Ballou", "Bamba Thialène", "Bani Israel", "Boutoucoufara", "Boynguel Bamba", "Bélé", "Dialacoto Missirah", "Dianké Makha", "Dougué", "Gabou", "Goudiry", "Goumbayel", "Kahène", "Koar", "Komoti", "Koulor", "Koupentoum", "Koussan", "Koussanar", "Kouthiaba Wolof", "Madina Foulbé", "Makacolibantang", "Malème Niani", "Moudery", "Ndame", "Ndoga Babacar", "Niani Toucouleur", "Néttéboulou", "Payar", "Sinthiou Bocar Aly", "Sinthiou Fissa", "Sinthiou Malème", "Sinthiou Mamadou Boubou", "Tamba", "Toumboura Sadatou"],
  Kedougou: ["Bandafassi", "Bembou", "Dakatéli", "Dar Salam", "Dimboli", "Dindefelo Ninéfécha", "Ethiolo", "Fongolimbi", "Kedougou", "Khossanto", "Missirah Sirimana", "Médina Baffé", "Oubadj", "Sabodala", "Salemata", "Saraya", "Thiankoye", "Tomboroncoto"],
  Kolda: ["Bignarabé", "Bonconto", "Bourouco", "Dinguiraye", "Dioulacolon", "Guiro Yéro Bocar", "Kandia", "Kandiaye", "Kolda", "Koulinto", "Kéréwane", "Linkering", "Medina Yoro Foulah", "Médina El Hadj", "Médina Gounass", "Ndorna", "Niaming", "Némataba", "Ouassadou", "Pakour", "Paroumba", "Saré Bidji", "Saré Coly Sallé", "Sinthiang Koundara", "Tankanto Escale", "Thiétty", "Velingara"],
  Ziguinchor: ["Adéane", "Balinghore", "Bignona", "Boutoupa Camaracounda", "Coubalan", "Diembéring", "Diégoune", "Djibidione", "Djinaky", "Enampore", "Kafontine", "Kartiack", "Kataba 1", "Mangagoulack", "Mlom", "Mlomp", "Niaguis", "Niamone Tenghori", "Niassia", "Oukout", "Oulampane", "Ouonck", "Oussouye", "Santhiaba Manjack", "Sindian", "Suelle", "Ziguinchor"],
  Sedhiou: ["Bambaly", "Boghal", "Bona", "Bounkiling", "Bémet Bidjini", "Diacounda", "Diambati", "Diaroumé", "DIENDE Oudoucar", "Diendé", "Diouboudou", "Djibabouya", "Djibanar", "Djiredji", "Faoune", "Goudomp", "Inor", "Kandion Mangana", "Kaour", "Karantaba", "Kolibantang", "Koussy", "Mangaroungou Santo", "Ndiamacouta", "Niagha", "Sakar", "San Samba", "Sedhiou", "Simbandi Balante", "Simbandi Brassou", "Tankon", "Yarang Balante"],
}

/** Communes d'une région (triées), [] si inconnue. */
export function communesForRegion(region: string | null | undefined): readonly string[] {
  if (!region) return []
  return COMMUNES_BY_REGION[region as RegionValue] ?? []
}
