import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Brand
        'gj-teal':        'var(--gj-teal)',
        'gj-teal-deep':   'var(--gj-teal-deep)',
        'gj-teal-deep-2': 'var(--gj-teal-deep-2)',
        'gj-teal-soft':   'var(--gj-teal-soft)',
        'gj-yellow':      'var(--gj-yellow)',
        'gj-yellow-soft': 'var(--gj-yellow-soft)',
        'gj-yellow-ink':  'var(--gj-yellow-ink)',
        'gj-red':         'var(--gj-red)',
        'gj-red-soft':    'var(--gj-red-soft)',
        'gj-red-ink':     'var(--gj-red-ink)',
        'gj-blue':        'var(--gj-blue)',
        'gj-blue-soft':   'var(--gj-blue-soft)',
        'gj-blue-ink':    'var(--gj-blue-ink)',
        'gj-green':       'var(--gj-green)',
        'gj-green-soft':  'var(--gj-green-soft)',
        'gj-green-ink':   'var(--gj-green-ink)',
        'gj-indigo':      'var(--gj-indigo)',
        'gj-indigo-soft': 'var(--gj-indigo-soft)',
        'gj-whatsapp':    'var(--gj-whatsapp)',
        // Neutres
        'gj-ink':         'var(--gj-ink)',
        'gj-grey':        'var(--gj-grey)',
        'gj-grey-2':      'var(--gj-grey-2)',
        'gj-line':        'var(--gj-line)',
        'gj-line-strong': 'var(--gj-line-strong)',
        'gj-bg':          'var(--gj-bg)',
        'gj-surface':     'var(--gj-surface)',
        // Sémantiques
        'color-action-primary':   'var(--color-action-primary)',
        'color-action-secondary': 'var(--color-action-secondary)',
        'color-text-primary':     'var(--color-text-primary)',
        'color-text-secondary':   'var(--color-text-secondary)',
        'color-text-muted':       'var(--color-text-muted)',
        'color-text-link':        'var(--color-text-link)',
        'color-bg-page':          'var(--color-bg-page)',
        'color-bg-surface':       'var(--color-bg-surface)',
        'color-border-default':   'var(--color-border-default)',
        'color-border-strong':    'var(--color-border-strong)',
        'color-status-danger':    'var(--color-status-danger)',
        'color-status-danger-bg': 'var(--color-status-danger-bg)',
        'color-status-success':   'var(--color-status-success)',
        'color-status-success-bg':'var(--color-status-success-bg)',
        // Aliases CJS legacy
        'cjs-vert':       'var(--gj-teal)',
        'cjs-vert-clair': 'var(--gj-teal-deep)',
        'cjs-or':         'var(--gj-yellow)',
        'cjs-rouge':      'var(--gj-red)',
        'cjs-noir':       'var(--gj-ink)',
        'cjs-gris':       'var(--gj-grey)',
        'cjs-fond':       'var(--gj-bg)',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', '"Segoe UI"', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'fs-100': ['var(--fs-100)', { lineHeight: 'var(--gj-lh-body)' }],
        'fs-200': ['var(--fs-200)', { lineHeight: 'var(--gj-lh-body)' }],
        'fs-300': ['var(--fs-300)', { lineHeight: 'var(--gj-lh-body)' }],
        'fs-400': ['var(--fs-400)', { lineHeight: 'var(--gj-lh-body)' }],
        'fs-500': ['var(--fs-500)', { lineHeight: 'var(--gj-lh-tight)' }],
        'fs-600': ['var(--fs-600)', { lineHeight: 'var(--gj-lh-tight)' }],
        'fs-700': ['var(--fs-700)', { lineHeight: 'var(--gj-lh-tight)' }],
        'fs-800': ['var(--fs-800)', { lineHeight: 'var(--gj-lh-tight)' }],
        'fs-900': ['var(--fs-900)', { lineHeight: 'var(--gj-lh-tight)' }],
      },
      borderRadius: {
        'gj-xs':   'var(--gj-r-xs)',
        'gj-sm':   'var(--gj-r-sm)',
        'gj-md':   'var(--gj-r-md)',
        'gj-lg':   'var(--gj-r-lg)',
        'gj-xl':   'var(--gj-r-xl)',
        'gj-2xl':  'var(--gj-r-2xl)',
        'gj-pill': 'var(--gj-r-pill)',
        'cjs':     '8px',
      },
      spacing: {
        'tap':     'var(--tap-min)',
        'tap-c':   'var(--tap-comfortable)',
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-5': 'var(--space-5)',
        'space-6': 'var(--space-6)',
        'space-7': 'var(--space-7)',
        'space-8': 'var(--space-8)',
      },
      boxShadow: {
        'gj-sm':  'var(--gj-shadow-sm)',
        'gj-md':  'var(--gj-shadow-md)',
        'gj-lg':  'var(--gj-shadow-lg)',
        'gj-nav': 'var(--gj-shadow-bottom-nav)',
      },
      zIndex: {
        'nav':    'var(--gj-z-nav)',
        'fbar':   'var(--gj-z-fbar)',
        'bnav':   'var(--gj-z-bottom-nav)',
        'chat':   'var(--gj-z-chat)',
        'overlay':'var(--gj-z-overlay)',
        'toast':  'var(--gj-z-toast)',
      },
    },
  },
  plugins: [],
}

export default config
