export { ProfilHeader }       from './ProfilHeader'
export { CompletionBar }      from './CompletionBar'
export { SectionIdentite }    from './SectionIdentite'
export { SectionProfil }      from './SectionProfil'
export { SectionExperiences } from './SectionExperiences'
export { SectionCertificats } from './SectionCertificats'
