export { ProfilHeader }       from './ProfilHeader'
export { CompletionBar }      from './CompletionBar'
export { ProfilClient }       from './ProfilClient'
export { SectionIdentite }    from './SectionIdentite'
export { SectionProfil }      from './SectionProfil'
export { SectionExperiences } from './SectionExperiences'
export { SectionDiplomes }    from './SectionDiplomes'
export { SectionCertificats } from './SectionCertificats'
